print("Здравствуйте!")
print("Пожалуйста, укажите ваше имя: ")
your_name = input()
my_string = input('Какой курс Вы выбрали?: ')
print("Поздравляем! Желаем успеха в Вашем обучении!", my_string,',' "Дмитрий.")
print(len(my_string))
print('Разработчик Python' .upper())
print('Разработчик Python' .lower())
print('Р аз раб  отчик:Pyth on .'.replace(' ', ''))
print(my_string[0])
print(my_string[-1])

